### ISSUE TITLE
Relationship to SymbolicUtils etc

### ISSUE THREAD

**Issue by cscherrer** [JuliaSymbolics/TermInterface.jl#15]
Hi,

Documentation for this package says,
> Its purpose is to provide a shared interface between various symbolic programming Julia packages, for example [SymbolicUtils.jl](https://github.com/JuliaSymbolics/SymbolicUtils.jl), [Symbolics.jl](https://github.com/JuliaSymbolics/Symbolics.jl) and [Metatheory.jl](https://github.com/0x0f0f0f/Metatheory.jl).

But SymbolicUtils doesn't depend on it, and in fact seems incompatible:

```julia
julia> using SymbolicUtils; import TermInterface

julia> @syms x::Int
(x,)

julia> TermInterface.exprhead(x + 1)
ERROR: MethodError: no method matching exprhead(::SymbolicUtils.BasicSymbolic{Int64})

Closest candidates are:
  exprhead(::Expr)
   @ TermInterface ~/.julia/packages/TermInterface/6hcD2/src/expr.jl:5

Stacktrace:
 [1] top-level scope
   @ REPL[2]:1
```

Digging into this, I came across https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/505 from a few months ago.

Given this, what is the current and planned relationship of this package to the rest of the ecosystem? Will it be deprecated? If we want to program to an interface to make it easy to use tools from the JuliaSymbolics ecosystem, what's now the "right" way to do that?

**Comment by ChrisRackauckas** [comment]
It basically got deprecated. @shashi can comment on his future plans.

**Comment by 0x0f0f0f** [comment]
@cscherrer latest deployed version will be re-integrated with Metatheory.jl (already is on [this branch](https://github.com/JuliaSymbolics/Metatheory.jl/pull/185)) and likely with SymbolicUtils and dependants

**Comment by shashi** [comment]
Terminterface dependency is merged back in.
