### ISSUE TITLE
expr vs call?

### ISSUE THREAD

**Issue by nsajko** [JuliaSymbolics/TermInterface.jl#31]
I don't understand the difference between `isexpr` and `iscall`. Perhaps give in the docs an example: a type `T` and `x::T` such that `isexpr(x) != iscall(x)`?

**Comment by nsajko** [comment]
Example that helped me understand:

```julia-repl
julia> using TermInterface

julia> e = :(x + 2)
:(x + 2)

julia> isexpr(e)
true

julia> iscall(e)
true

julia> head(e)
:call

julia> children(e)
3-element Vector{Any}:
  :+
  :x
 2

julia> operation(e)
:+

julia> arguments(e)
2-element view(::Vector{Any}, 2:3) with eltype Any:
  :x
 2
```

**Comment by nsajko** [comment]
Actually, I still don't understand what are the semantics of `head` and `children` supposed to be. To be specific, I want to implement the TermInterface interface for several of my types.

E.g., suppose I have a type like this:

```julia
struct Expression
  operation
  arguments::Vector{Any}
end
```

Clearly I need these:

```julia
TermInterface.iscall(::Expression) = true
TermInterface.operation(e::Expression) = e.operation
TermInterface.arguments(e::Expression) = e.arguments
```

But what about `isexpr`, `head` or `children`?

**Comment by nsajko** [comment]
Thanks for the explanation!

> Thanks for all the fixes and reports!

You're welcome!

> What are you working on?

[CallableExpressions.jl](https://gitlab.com/nsajko/CallableExpressions.jl). The main branch should now support TermInterface.jl. The package extension gives the same definition for `TermInterface.children` as for `TermInterface.arguments`. Similarly with `TermInterface.operation` and `TermInterface.head`. That's OK, right? This is the code:

https://gitlab.com/nsajko/CallableExpressions.jl/-/blob/e56fe884db08a2a17d42acb9fb74c35113a79fbe/ext/TermInterfaceExt.jl#L3-34

> Wanna get in touch on Zulip/Slack ?

Sure, is there a group or something?

**Comment by 0x0f0f0f** [comment]
> Sure, is there a group or something?

Yes, the #metatheory stream on Julia Zulip
