### ISSUE TITLE
outdated doc string copies in the README

### ISSUE THREAD

**Issue by nsajko** [JuliaSymbolics/TermInterface.jl#41]
PRs #35 and #39 failed to update the doc string copies in the README. They need to either:

1. be updated or
2. deleted from the README as redundant, as the doc strings should already be included in the autogenerated JuliaHub docs

**Comment by ChrisRackauckas** [comment]
We should delete them from the readme and just make a real doc.

**Comment by 0x0f0f0f** [comment]
Forgot `maketerm`. Makes sense to make a real doc.

**Comment by 0x0f0f0f** [comment]
@ChrisRackauckas @nsajko Made #42

**Comment by 0x0f0f0f** [comment]
https://juliasymbolics.github.io/TermInterface.jl/dev/
